const DUMMYPRODUCTS = {
    "products": [
        {
            "_id": "6232b59e8a80dc3de4536601",
            "product_id": "1",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "jacket",
            "p_cat_id": "jacket",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies jackets",
            "product_img1": "jac1.jpg",
            "product_img2": "jac2.jpg",
            "product_img3": "jac3.jpg",
            "product_price": "25",
            "product_desc": "leader jacket",
            "product_keyword": "ladies jacket",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": true,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.228Z",
            "updatedAt": "2022-03-17T04:14:22.228Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536603",
            "product_id": "15",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men t-shirt",
            "product_img1": "ts3.jpg",
            "product_img2": "ts2.jpg",
            "product_img3": "ts1.jpg",
            "product_price": "10",
            "product_desc": "men T-shirt",
            "product_keyword": "men T-shirt",
            "stock": "4",
            "product_rating": "3.5",
            "product_color": "black",
            "product_size": "x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.264Z",
            "updatedAt": "2022-03-17T04:14:22.264Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536605",
            "product_id": "16",
            "m_cat_id": "null",
            "w_cat_id": "dress",
            "k_cat_id": "dress",
            "p_cat_id": "dress",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kids dress",
            "product_img1": "kid1.jpg",
            "product_img2": "kid.jpg",
            "product_img3": "kid1.jpg",
            "product_price": "15",
            "product_desc": "kids dress",
            "product_keyword": "kids dress",
            "stock": "6",
            "product_rating": "5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.294Z",
            "updatedAt": "2022-03-17T04:14:22.294Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536607",
            "product_id": "17",
            "m_cat_id": "null",
            "w_cat_id": "dress",
            "k_cat_id": "dress",
            "p_cat_id": "dress",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kids dress",
            "product_img1": "kid4.jpg",
            "product_img2": "kid3.jpg",
            "product_img3": "kid4.jpg",
            "product_price": "10",
            "product_desc": "kids dress",
            "product_keyword": "kids dress",
            "stock": "5",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.320Z",
            "updatedAt": "2022-03-17T04:14:22.320Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536609",
            "product_id": "18",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shoes",
            "product_img1": "kidsh1.jpg",
            "product_img2": "kidsh2.jpg",
            "product_img3": "kidsh3.jpg",
            "product_price": "20",
            "product_desc": "kid shoes",
            "product_keyword": "kid shoes",
            "stock": "9",
            "product_rating": "1.5",
            "product_color": "black",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.347Z",
            "updatedAt": "2022-03-17T04:14:22.347Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453660b",
            "product_id": "7",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "trouser",
            "p_cat_id": "trouser",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men trouser",
            "product_img1": "t6.jpg",
            "product_img2": "t7.jpg",
            "product_img3": "t8.jpg",
            "product_price": "20",
            "product_desc": "men trouser",
            "product_keyword": "men trouser",
            "stock": "10",
            "product_rating": "3",
            "product_color": "white",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.378Z",
            "updatedAt": "2022-03-17T04:14:22.378Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453660d",
            "product_id": "19",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Gucci men T-shirt",
            "product_img1": "T-shirt13.webp",
            "product_img2": "T-shirt14.webp",
            "product_img3": "T-shirt15.webp",
            "product_price": "15",
            "product_desc": "Gucci men T-shirt, 100% original",
            "product_keyword": "men T-shirt",
            "stock": "10",
            "product_rating": "3",
            "product_color": "black, gray, blue, yellow, red",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.426Z",
            "updatedAt": "2022-03-17T04:14:22.426Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453660f",
            "product_id": "20",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "null",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "sss11.jpg",
            "product_img2": "sss9.jpg",
            "product_img3": "sss10.jpg",
            "product_price": "25",
            "product_desc": "men shoes",
            "product_keyword": "men shoes",
            "stock": "10",
            "product_rating": "2",
            "product_color": "black",
            "product_size": "xl, x, m",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.473Z",
            "updatedAt": "2022-03-17T04:14:22.473Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536611",
            "product_id": "2",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "jacket",
            "p_cat_id": "jacket",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "boys-jacket",
            "product_img1": "ja4.jpg",
            "product_img2": "ja2.jpg",
            "product_img3": "ja3.jpg",
            "product_price": "12",
            "product_desc": "kids jacket",
            "product_keyword": "kids jacket",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.552Z",
            "updatedAt": "2022-03-17T04:14:22.552Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536613",
            "product_id": "3",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "sss.jpg",
            "product_img2": "FB_IMG_1578070542277.jpg",
            "product_img3": "s22.jpg",
            "product_price": "25",
            "product_desc": "men shoes",
            "product_keyword": "men shoes",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.605Z",
            "updatedAt": "2022-03-17T04:14:22.605Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536615",
            "product_id": "21",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shoes",
            "product_img1": "kidsh4.jpg",
            "product_img2": "kidsh6.jpg",
            "product_img3": "kidsh5.jpg",
            "product_price": "10",
            "product_desc": "kid shoes",
            "product_keyword": "kid shoes",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.664Z",
            "updatedAt": "2022-03-17T04:14:22.664Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536617",
            "product_id": "22",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men T-shirt",
            "product_img1": "T-shirt1.jpg",
            "product_img2": "T-shirt2.jpg",
            "product_img3": "T-shirt3.jpg",
            "product_price": "10",
            "product_desc": "men T-shirt",
            "product_keyword": "men T-shirt",
            "stock": "9",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.729Z",
            "updatedAt": "2022-03-17T04:14:22.729Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536619",
            "product_id": "23",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men shirt",
            "product_img1": "hmgoepprod (3).jpg",
            "product_img2": "hmgoepprod (7).jpg",
            "product_img3": "hmgoepprod (8).jpg",
            "product_price": "15",
            "product_desc": "men shirt",
            "product_keyword": "men shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.777Z",
            "updatedAt": "2022-03-17T04:14:22.777Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453661b",
            "product_id": "24",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "null",
            "p_cat_id": "jacket",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men  jacket",
            "product_img1": "men jacket1.jpg",
            "product_img2": "men jackket2.jpg",
            "product_img3": "men jacket1.jpg",
            "product_price": "14",
            "product_desc": "Black, nbsp, men jacket",
            "product_keyword": "men jacket",
            "stock": "4",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.801Z",
            "updatedAt": "2022-03-17T04:14:22.801Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453661d",
            "product_id": "25",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men shirt",
            "product_img1": "hmgoepprod (1).jpg",
            "product_img2": "hmgoepprod (10).jpg",
            "product_img3": "hmgoepprod (11).jpg",
            "product_price": "12",
            "product_desc": "Men shirt",
            "product_keyword": "Men shirt",
            "stock": "10",
            "product_rating": "3",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.871Z",
            "updatedAt": "2022-03-17T04:14:22.871Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de453661f",
            "product_id": "10",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "ss4.jpg",
            "product_img2": "ss5.jpg",
            "product_img3": "ss7.jpg",
            "product_price": "30",
            "product_desc": "men shoes",
            "product_keyword": "men shoes",
            "stock": "4",
            "product_rating": "2.5",
            "product_color": "black",
            "product_size": " xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.904Z",
            "updatedAt": "2022-03-17T04:14:22.904Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536621",
            "product_id": "26",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men T-shirt",
            "product_img1": "T-shirt4.jpg",
            "product_img2": "T-shirt5.jpg",
            "product_img3": "T-shirt6.jpg",
            "product_price": "10",
            "product_desc": "Men T-shirt",
            "product_keyword": "Men T-shirt",
            "stock": "10",
            "product_rating": "2",
            "product_color": "black",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.929Z",
            "updatedAt": "2022-03-17T04:14:22.929Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536623",
            "product_id": "4",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Ladies T-shirt",
            "product_img1": "top21.webp",
            "product_img2": "top22.webp",
            "product_img3": "top20.webp",
            "product_price": "15",
            "product_desc": "ladies T-shirt",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": true,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:22.959Z",
            "updatedAt": "2022-03-17T04:14:22.959Z",
            "__v": 0
        },
        {
            "_id": "6232b59e8a80dc3de4536625",
            "product_id": "27",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men trouser",
            "product_img1": "t5.jpg",
            "product_img2": "t9.jpg",
            "product_img3": "t4.jpg",
            "product_price": "17",
            "product_desc": "men trouser",
            "product_keyword": "new brand",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "black",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:22.997Z",
            "updatedAt": "2022-03-17T04:14:22.997Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536627",
            "product_id": "28",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men T-shirt",
            "product_img1": "T-shirt7.jpg",
            "product_img2": "T-shirt8.jpg",
            "product_img3": "T-shirt9.jpg",
            "product_price": "8",
            "product_desc": "Green Men T-shirt",
            "product_keyword": "Men T-shirt",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "black",
            "product_size": "xl, x, m",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.035Z",
            "updatedAt": "2022-03-17T04:14:23.035Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536629",
            "product_id": "5",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "levis T-shirt",
            "product_img1": "p22.jpg",
            "product_img2": "p21.jpg",
            "product_img3": "p24.jpg",
            "product_price": "15",
            "product_desc": "men T-shirt",
            "product_keyword": "men T-shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "white, black",
            "product_size": " m, xxl",
            "product_isFeatured": true,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.080Z",
            "updatedAt": "2022-03-17T04:14:23.080Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453662b",
            "product_id": "6",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies shoes",
            "product_img1": "lsho1.webp",
            "product_img2": "lsho.webp",
            "product_img3": "lsho2.webp",
            "product_price": "25",
            "product_desc": "women shoes",
            "product_keyword": "ladies shoes",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.110Z",
            "updatedAt": "2022-03-17T04:14:23.110Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453662d",
            "product_id": "29",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "null",
            "p_cat_id": "jacket",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men jacket",
            "product_img1": "jacket4.jpg",
            "product_img2": "jacket5.jpg",
            "product_img3": "jacket4.jpg",
            "product_price": "12",
            "product_desc": "Mixed nbsp, men jacket",
            "product_keyword": "men jacket",
            "stock": "5",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.132Z",
            "updatedAt": "2022-03-17T04:14:23.132Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453662f",
            "product_id": "8",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht21.webp",
            "product_img2": "sht22.webp",
            "product_img3": "sht23.webp",
            "product_price": "10",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "white, blue, brown",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.161Z",
            "updatedAt": "2022-03-17T04:14:23.161Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536631",
            "product_id": "30",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men trouser",
            "product_img1": "t1.jpg",
            "product_img2": "t2.jpg",
            "product_img3": "t1.jpg",
            "product_price": "13",
            "product_desc": "Men trouser",
            "product_keyword": "Men trouser",
            "stock": "7",
            "product_rating": "1.5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.204Z",
            "updatedAt": "2022-03-17T04:14:23.204Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536633",
            "product_id": "31",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "shirt10.png",
            "product_img2": "shirt11.png",
            "product_img3": "shirt10.png",
            "product_price": "15",
            "product_desc": "ladies Shirt",
            "product_keyword": "ladies Shirt",
            "stock": "10",
            "product_rating": "3.5",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.229Z",
            "updatedAt": "2022-03-17T04:14:23.229Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536635",
            "product_id": "32",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men T-shirt",
            "product_img1": "T-shirt10.jpg",
            "product_img2": "T-shirt11.jpg",
            "product_img3": "T-shirt12.jpg",
            "product_price": "10",
            "product_desc": "Men T-shirt",
            "product_keyword": "Men T-shirt",
            "stock": "5",
            "product_rating": "3.5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.260Z",
            "updatedAt": "2022-03-17T04:14:23.260Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536637",
            "product_id": "9",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "ss1.jpg",
            "product_img2": "ss2.jpg",
            "product_img3": "ss3.jpg",
            "product_price": "35",
            "product_desc": "men shoes",
            "product_keyword": "men shoes",
            "stock": "3",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "x",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.300Z",
            "updatedAt": "2022-03-17T04:14:23.300Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536639",
            "product_id": "33",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "null",
            "p_cat_id": "jacket",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies jackets",
            "product_img1": "jacket3.jpg",
            "product_img2": "jacket2.jpg",
            "product_img3": "jacket1.jpg",
            "product_price": "12",
            "product_desc": "ladies jacket",
            "product_keyword": "ladies jacket",
            "stock": "10",
            "product_rating": "2",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.322Z",
            "updatedAt": "2022-03-17T04:14:23.322Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536643",
            "product_id": "11",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shoes",
            "product_img1": "kisho1.jpg",
            "product_img2": "kisho2.jpg",
            "product_img3": "kisho3.jpg",
            "product_price": "15",
            "product_desc": "kid shoes",
            "product_keyword": "kid shoes",
            "stock": "4",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.506Z",
            "updatedAt": "2022-03-17T04:14:23.506Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536645",
            "product_id": "38",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "Baby shoes",
            "product_img1": "kidshh.JPG",
            "product_img2": "kidsh0.JPG",
            "product_img3": "kidsh.JPG",
            "product_price": "8",
            "product_desc": "kid sneakers shoes, 100% original, 100% new brand, Leather shoes, Shinny sneakers children",
            "product_keyword": "kid shoes",
            "stock": "5",
            "product_rating": "2.5",
            "product_color": "black, white, pink, blue",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.543Z",
            "updatedAt": "2022-03-17T04:14:23.543Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536647",
            "product_id": "39",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shirt",
            "product_img1": "s3.jpg",
            "product_img2": "s1.jpg",
            "product_img3": "s2.jpg",
            "product_price": "10",
            "product_desc": "men shirtr, Jeans Men shirtr, very smooth",
            "product_keyword": "men shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.587Z",
            "updatedAt": "2022-03-17T04:14:23.587Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536649",
            "product_id": "40",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "null",
            "p_cat_id": "jacket",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men jacket",
            "product_img1": "men jacket3.jpg",
            "product_img2": "men jacket4.jpg",
            "product_img3": "men jacket3.jpg",
            "product_price": "25",
            "product_desc": "Men jacket, 100% original product, 100% leather",
            "product_keyword": "men jacket",
            "stock": "4",
            "product_rating": "1",
            "product_color": "black, white, gray",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:23.617Z",
            "updatedAt": "2022-03-17T04:14:23.617Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453664b",
            "product_id": "41",
            "m_cat_id": "jacket",
            "w_cat_id": "jacket",
            "k_cat_id": "null",
            "p_cat_id": "jacket",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Black Jacket",
            "product_img1": "men jacket5.jpg",
            "product_img2": "men jacket6.jpg",
            "product_img3": "men jacket5.jpg",
            "product_price": "20",
            "product_desc": "Black men jacket, 100% original product, 100% leather ",
            "product_keyword": "men jacket",
            "stock": "10",
            "product_rating": "1",
            "product_color": "white, black, gray",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.655Z",
            "updatedAt": "2022-03-17T04:14:23.655Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453664d",
            "product_id": "12",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies shoes",
            "product_img1": "l2.jpg",
            "product_img2": "l1.jpg",
            "product_img3": "l3.jpg",
            "product_price": "20",
            "product_desc": "ladies shoes",
            "product_keyword": "ladies shoes",
            "stock": "7",
            "product_rating": "1.5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.724Z",
            "updatedAt": "2022-03-17T04:14:23.724Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de453664f",
            "product_id": "42",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "null",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "sh4.jpg",
            "product_img2": "sh6.jpg",
            "product_img3": "sh8.jpg",
            "product_price": "12",
            "product_desc": "Men shoes, 100% original product, 100% new brand",
            "product_keyword": "men shoes",
            "stock": "3",
            "product_rating": "4.5",
            "product_color": "black, white, red",
            "product_size": "xl, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.785Z",
            "updatedAt": "2022-03-17T04:14:23.785Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536651",
            "product_id": "14",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "trouser",
            "p_cat_id": "trouser",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "Men trouser",
            "product_img1": "tr2.jpg",
            "product_img2": "tr1.jpg",
            "product_img3": "tr3.jpg",
            "product_price": "12",
            "product_desc": "men trouser",
            "product_keyword": "men trouser",
            "stock": "8",
            "product_rating": "3",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.813Z",
            "updatedAt": "2022-03-17T04:14:23.813Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536653",
            "product_id": "43",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies top",
            "product_img1": "top1.webp",
            "product_img2": "top0.webp",
            "product_img3": "top2.webp",
            "product_price": "10",
            "product_desc": "ladies Top, 100% original ",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black, pink, brown, blue",
            "product_size": "xl, x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.869Z",
            "updatedAt": "2022-03-17T04:14:23.869Z",
            "__v": 0
        },
        {
            "_id": "623876a0fabac137d28cb0d1",
            "product_id": "44",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies t-shirt",
            "product_img1": "top3.jpg",
            "product_img2": "top4.webp",
            "product_img3": "top5.jpg",
            "product_price": "9",
            "product_desc": "ladies T-shirt, 100% original",
            "product_keyword": "ladies T-shirt",
            "stock": "4",
            "product_rating": "4",
            "product_color": "black, lightblue, orange, red",
            "product_size": "x, xl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.909Z",
            "updatedAt": "2022-03-17T04:14:23.909Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536657",
            "product_id": "45",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies top",
            "product_img1": "top6.webp",
            "product_img2": "top6.webp",
            "product_img3": "top6.webp",
            "product_price": "8",
            "product_desc": "ladies Top, 100% original, 100% new Brand",
            "product_keyword": "ladies T-shirt",
            "stock": "6",
            "product_rating": "5",
            "product_color": "black, white, red",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.936Z",
            "updatedAt": "2022-03-17T04:14:23.936Z",
            "__v": 0
        },
        {
            "_id": "6232b59f8a80dc3de4536659",
            "product_id": "46",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies T-Shirt",
            "product_img1": "top7.webp",
            "product_img2": "top7.webp",
            "product_img3": "top7.webp",
            "product_price": "9",
            "product_desc": "ladies T-shirt, 100% original, 100% & nbsp; new brand",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "black, white, red, yellow",
            "product_size": "xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:23.986Z",
            "updatedAt": "2022-03-17T04:14:23.986Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453665b",
            "product_id": "47",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Mom T-shirt",
            "product_img1": "top9.webp",
            "product_img2": "top10.webp",
            "product_img3": "top8.webp",
            "product_price": "10",
            "product_desc": "ladies T-shirt, 100% original, 100% new brand",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "white, gray",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.040Z",
            "updatedAt": "2022-03-17T04:14:24.040Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453665d",
            "product_id": "48",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Love T-shirt",
            "product_img1": "top12.webp",
            "product_img2": "top13.webp",
            "product_img3": "top11.webp",
            "product_price": "10",
            "product_desc": "Love T-shirt, 100% original, 100% new Brand",
            "product_keyword": "ladies T-shirt",
            "stock": "4",
            "product_rating": "2.5",
            "product_color": "white, gray",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.069Z",
            "updatedAt": "2022-03-17T04:14:24.069Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453665f",
            "product_id": "49",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies T-Shirt",
            "product_img1": "top15.webp",
            "product_img2": "top16.webp",
            "product_img3": "top14.webp",
            "product_price": "12",
            "product_desc": "Ladies T-shirt, 100% original, 100% new Brand",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "black, gray, pink, brown, orange",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.099Z",
            "updatedAt": "2022-03-17T04:14:24.099Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536661",
            "product_id": "50",
            "m_cat_id": "t-shirt",
            "w_cat_id": "t-shirt",
            "k_cat_id": "null",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies T-Shirt",
            "product_img1": "top18.webp",
            "product_img2": "top19.webp",
            "product_img3": "top17.webp",
            "product_price": "13",
            "product_desc": "ladies T-Shirt, Long sleeve, 100% original",
            "product_keyword": "ladies T-shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "gray, white",
            "product_size": "xl, x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.140Z",
            "updatedAt": "2022-03-17T04:14:24.140Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536663",
            "product_id": "51",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Jeans Shirts",
            "product_img1": "sht3.webp",
            "product_img2": "sht4.webp",
            "product_img3": "sht5.webp",
            "product_price": "15",
            "product_desc": "Jeans Shirt nbsp, 100% original, 100% jeans",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "blue, darkblue, black",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.168Z",
            "updatedAt": "2022-03-17T04:14:24.168Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536665",
            "product_id": "52",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht0.webp",
            "product_img2": "sht1.webp",
            "product_img3": "sht2.webp",
            "product_price": "12",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "4.5",
            "product_color": "black, white, brown",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.187Z",
            "updatedAt": "2022-03-17T04:14:24.187Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536667",
            "product_id": "53",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht7.webp",
            "product_img2": "sht8.webp",
            "product_img3": "sht6.webp",
            "product_price": "10",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "4",
            "product_rating": "5",
            "product_color": "white, blue, brown",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.213Z",
            "updatedAt": "2022-03-17T04:14:24.213Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536669",
            "product_id": "54",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht9.webp",
            "product_img2": "sht10.webp",
            "product_img3": "sht11.webp",
            "product_price": "12",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "white, red, brown",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.243Z",
            "updatedAt": "2022-03-17T04:14:24.243Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453666b",
            "product_id": "55",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht13.webp",
            "product_img2": "sht12.webp",
            "product_img3": "sht14.webp",
            "product_price": "10",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "1",
            "product_color": "white, blue, pink",
            "product_size": "xl, x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.267Z",
            "updatedAt": "2022-03-17T04:14:24.267Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453666d",
            "product_id": "56",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht17.webp",
            "product_img2": "sht16.webp",
            "product_img3": "sht15.webp",
            "product_price": "8",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "white, yellow, blue",
            "product_size": "xl, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.289Z",
            "updatedAt": "2022-03-17T04:14:24.289Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453666f",
            "product_id": "57",
            "m_cat_id": "shirt",
            "w_cat_id": "shirt",
            "k_cat_id": "null",
            "p_cat_id": "shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies Shirt",
            "product_img1": "sht20.webp",
            "product_img2": "sht19.webp",
            "product_img3": "sht18.webp",
            "product_price": "15",
            "product_desc": "ladies shirt, 100% original, 100% new brand",
            "product_keyword": "ladies shirt",
            "stock": "10",
            "product_rating": "5",
            "product_color": "white, green, brown",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.315Z",
            "updatedAt": "2022-03-17T04:14:24.315Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536671",
            "product_id": "58",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies trouser",
            "product_img1": "tro0.webp",
            "product_img2": "tro1.webp",
            "product_img3": "tro2.webp",
            "product_price": "15",
            "product_desc": "ladies trousers, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "10",
            "product_rating": "5",
            "product_color": "black, brown, gray",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.343Z",
            "updatedAt": "2022-03-17T04:14:24.343Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536673",
            "product_id": "59",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Jeans trousers",
            "product_img1": "tro6.webp",
            "product_img2": "tro7.webp",
            "product_img3": "tro8.webp",
            "product_price": "15",
            "product_desc": "ladies jeans trouser, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "10",
            "product_rating": "1",
            "product_color": "blue, darkblue, black, gray",
            "product_size": "x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.371Z",
            "updatedAt": "2022-03-17T04:14:24.371Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536675",
            "product_id": "60",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies trousers",
            "product_img1": "tro4.webp",
            "product_img2": "trp3.webp",
            "product_img3": "tro5.webp",
            "product_price": "8",
            "product_desc": "ladies trousers, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "5",
            "product_rating": "4",
            "product_color": "black, red, white, gray",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.402Z",
            "updatedAt": "2022-03-17T04:14:24.402Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536677",
            "product_id": "61",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Fashion Jeans",
            "product_img1": "tro9.webp",
            "product_img2": "tro10.webp",
            "product_img3": "tro12.webp",
            "product_price": "14",
            "product_desc": "Fashion ladies trousers, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "9",
            "product_rating": "5",
            "product_color": "black, brown, gray",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.431Z",
            "updatedAt": "2022-03-17T04:14:24.431Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536679",
            "product_id": "62",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Jeans trousers",
            "product_img1": "tro13.webp",
            "product_img2": "tro14.webp",
            "product_img3": "tro15.webp",
            "product_price": "16",
            "product_desc": "New Fashion ladies trousers, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "6",
            "product_rating": "5",
            "product_color": "black, blue, gray",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.450Z",
            "updatedAt": "2022-03-17T04:14:24.450Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453667b",
            "product_id": "63",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "null",
            "p_cat_id": "trouser",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Jeans trousers",
            "product_img1": "tro16.jpg",
            "product_img2": "tro17.jpg",
            "product_img3": "tro18.jpg",
            "product_price": "12",
            "product_desc": "Jeans ladies trousers, 100% original, 100% new brand",
            "product_keyword": "ladies trousers",
            "stock": "2",
            "product_rating": "2.5",
            "product_color": "black, darkblue, lightblue",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.475Z",
            "updatedAt": "2022-03-17T04:14:24.475Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453667d",
            "product_id": "64",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "null",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies boot",
            "product_img1": "lsho3.webp",
            "product_img2": "lsho4.webp",
            "product_img3": "lsho5.webp",
            "product_price": "8",
            "product_desc": "ladies shoes, 100% original, warm snow boots ",
            "product_keyword": "ladies shoes",
            "stock": "6",
            "product_rating": "5",
            "product_color": "black, red, green, gray",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.504Z",
            "updatedAt": "2022-03-17T04:14:24.504Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453667f",
            "product_id": "65",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "null",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies office shoes",
            "product_img1": "lsho7.webp",
            "product_img2": "lsho8.webp",
            "product_img3": "lsho6.webp",
            "product_price": "10",
            "product_desc": "ladies shoes, 100% original, Office ladies shoes",
            "product_keyword": "ladies shoes",
            "stock": "10",
            "product_rating": "5",
            "product_color": "black, red, green, gray",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.536Z",
            "updatedAt": "2022-03-17T04:14:24.536Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536681",
            "product_id": "66",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "null",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Elegant ladies shoes",
            "product_img1": "lsho12.webp",
            "product_img2": "lsho13.webp",
            "product_img3": "lsho14.webp",
            "product_price": "25",
            "product_desc": "Elegant ladies shoes, 100% original, African style Elegant ladies shoes, High heel ladies shoes",
            "product_keyword": "ladies shoes",
            "stock": "8",
            "product_rating": "5",
            "product_color": "blue, red, pink, white",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.557Z",
            "updatedAt": "2022-03-17T04:14:24.557Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536683",
            "product_id": "67",
            "m_cat_id": "null",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "ladies boot",
            "product_img1": "lsho9.webp",
            "product_img2": "lsho10.webp",
            "product_img3": "lsho11.webp",
            "product_price": "20",
            "product_desc": "ladies boot shoes, 100% original, Ladies shoes, waterproof Genuine leather, nbsp, High heeled ladies shoes quality",
            "product_keyword": "ladies shoes",
            "stock": "10",
            "product_rating": "5",
            "product_color": "black, gray, brown",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.594Z",
            "updatedAt": "2022-03-17T04:14:24.594Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536685",
            "product_id": "68",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid sneakers shoes",
            "product_img1": "ksh0.webp",
            "product_img2": "ksh2.webp",
            "product_img3": "ksh1.webp",
            "product_price": "7",
            "product_desc": "kid sneakers shoes, 100% original, 100% new brand, Leather shoes",
            "product_keyword": "kid shoes",
            "stock": "7",
            "product_rating": "5",
            "product_color": "black, white, pink",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.636Z",
            "updatedAt": "2022-03-17T04:14:24.636Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536687",
            "product_id": "69",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "Glowing Sneakers",
            "product_img1": "ksh4.jpg",
            "product_img2": "ksh3.jpg",
            "product_img3": "ksh5.jpg",
            "product_price": "15",
            "product_desc": "kid sneakers shoes, 100% original, 100% new brand, Leather shoes, Glowing sneakers children",
            "product_keyword": "kid shoes",
            "stock": "7",
            "product_rating": "5",
            "product_color": "black, white, pink, blue",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.672Z",
            "updatedAt": "2022-03-17T04:14:24.672Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536689",
            "product_id": "70",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shoes",
            "product_img1": "ksh6.webp",
            "product_img2": "ksh8.webp",
            "product_img3": "ksh7.webp",
            "product_price": "12",
            "product_desc": "kid shoes, 100% original, 100% new brand, soft sport shoes",
            "product_keyword": "kid shoes",
            "stock": "7",
            "product_rating": "5",
            "product_color": "black, blue, pink",
            "product_size": "xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.699Z",
            "updatedAt": "2022-03-17T04:14:24.699Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453668b",
            "product_id": "71",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shirts",
            "product_img1": "kshirt3.jpg",
            "product_img2": "kshirt1.jpg",
            "product_img3": "kshirt2.jpg",
            "product_price": "10",
            "product_desc": "kid shirts, cute lovely shirts, 100% original & nbsp",
            "product_keyword": "kid shirts",
            "stock": "3",
            "product_rating": "5",
            "product_color": "red, blue, green",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.734Z",
            "updatedAt": "2022-03-17T04:14:24.734Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453668d",
            "product_id": "72",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "cartoon T-shirt",
            "product_img1": "ktsh0.webp",
            "product_img2": "ktsh1.webp",
            "product_img3": "ktsh2.webp",
            "product_price": "8",
            "product_desc": "cartoon T-shirt, Boys and girl 3D cat T-shirt, Cute cat T-shirt, 100% original",
            "product_keyword": "kid t-shirt",
            "stock": "10",
            "product_rating": "2.5",
            "product_color": "black",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.778Z",
            "updatedAt": "2022-03-17T04:14:24.778Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de453668f",
            "product_id": "73",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "Girls T-shirt",
            "product_img1": "ktsh3.webp",
            "product_img2": "ktsh4.webp",
            "product_img3": "ktsh5.webp",
            "product_price": "12",
            "product_desc": "Girls T-shirt, 100% original, Cute & nbsp; T-shirt",
            "product_keyword": "kid t-shirt",
            "stock": "10",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.810Z",
            "updatedAt": "2022-03-17T04:14:24.810Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536691",
            "product_id": "74",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "cartoon T-shirt",
            "product_img1": "ktsh6.webp",
            "product_img2": "ktsh7.webp",
            "product_img3": "ktsh8.webp",
            "product_price": "7",
            "product_desc": "cartoon T-shirt, Boys and girls 3D cartoon T-shirt, Cute cat T-shirt",
            "product_keyword": "kid t-shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.842Z",
            "updatedAt": "2022-03-17T04:14:24.842Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536693",
            "product_id": "75",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "kids",
            "date": "2021-04-23 16:25:53",
            "product_title": "Print T-shirt",
            "product_img1": "ktsh9.webp",
            "product_img2": "ktsh11.webp",
            "product_img3": "ktsh10.webp",
            "product_price": "7",
            "product_desc": "Print T-shirt, Number children T-shirt",
            "product_keyword": "kid t-shirt",
            "stock": "5",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "xl, x",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.863Z",
            "updatedAt": "2022-03-17T04:14:24.863Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536695",
            "product_id": "76",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "t-shirt",
            "p_cat_id": "t-shirt",
            "cat_id": "women",
            "date": "2021-04-10 15:34:21",
            "product_title": "Love T-shirt",
            "product_img1": "ktsh12.webp",
            "product_img2": "ktsh13.webp",
            "product_img3": "ktsh14.webp",
            "product_price": "8",
            "product_desc": "Love T-shirt, I Love My Sister/Brother kid T-shirt, short sleeve T-shirt, 100% original T0shirt, nbsp;",
            "product_keyword": "kid t-shirt",
            "stock": "10",
            "product_rating": "4",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": true,
            "createdAt": "2022-03-17T04:14:24.907Z",
            "updatedAt": "2022-03-17T04:14:24.907Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536697",
            "product_id": "77",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shirts",
            "product_img1": "ksht0.webp",
            "product_img2": "ksht1.webp",
            "product_img3": "ksht2.webp",
            "product_price": "6",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "10",
            "product_rating": "5",
            "product_color": "black",
            "product_size": "m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.937Z",
            "updatedAt": "2022-03-17T04:14:24.937Z",
            "__v": 0
        },
        {
            "_id": "6232b5a08a80dc3de4536699",
            "product_id": "78",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shirts",
            "product_img1": "ksht3.webp",
            "product_img2": "ksht4.webp",
            "product_img3": "ksht5.webp",
            "product_price": "8",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "3",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:24.971Z",
            "updatedAt": "2022-03-17T04:14:24.971Z",
            "__v": 0
        },
        {
            "_id": "6232b5a18a80dc3de453669b",
            "product_id": "79",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shirts",
            "product_img1": "ksht6.webp",
            "product_img2": "ksht7.webp",
            "product_img3": "ksht8.webp",
            "product_price": "7",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "10",
            "product_rating": "4.5",
            "product_color": "black",
            "product_size": "xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.015Z",
            "updatedAt": "2022-03-17T04:14:25.015Z",
            "__v": 0
        },
        {
            "_id": "6232b5a18a80dc3de453669d",
            "product_id": "80",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-10 15:34:21",
            "product_title": "kid shirts",
            "product_img1": "ksht9.webp",
            "product_img2": "ksht10.webp",
            "product_img3": "ksht11.webp",
            "product_price": "6",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "10",
            "product_rating": "1.5",
            "product_color": "white",
            "product_size": "x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.052Z",
            "updatedAt": "2022-03-17T04:14:25.052Z",
            "__v": 0
        },
        {
            "_id": "6232b5a18a80dc3de453669f",
            "product_id": "81",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-24 09:57:38",
            "product_title": "kid shirts",
            "product_img1": "kshirt4.jpg",
            "product_img2": "kishirt2.jpg",
            "product_img3": "kishirt3.jpg",
            "product_price": "10",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "8",
            "product_rating": "1.5",
            "product_color": "white",
            "product_size": "xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.232Z",
            "updatedAt": "2022-03-17T04:14:25.232Z",
            "__v": 0
        },
        {
            "_id": "6232b5a18a80dc3de45366a1",
            "product_id": "82",
            "m_cat_id": "null",
            "w_cat_id": "null",
            "k_cat_id": "shirt",
            "p_cat_id": "shirt",
            "cat_id": "kids",
            "date": "2021-04-24 09:37:54",
            "product_title": "kid shirts",
            "product_img1": "ksht12.webp",
            "product_img2": "ksht13.jpg",
            "product_img3": "ksht15.jpg",
            "product_price": "5",
            "product_desc": "Kids shirt, Lovely kid Shirt, Long sleeve kid shirt, We are all Friends kid shirt, 100% original shirt",
            "product_keyword": "kid shirts",
            "stock": "5",
            "product_rating": "1.5",
            "product_color": "white",
            "product_size": "x, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.296Z",
            "updatedAt": "2022-03-17T04:14:25.296Z",
            "__v": 0
        },
        {
            "_id": "62387aa1fabac137d28cb0d2",
            "product_id": "89",
            "m_cat_id": "trouser",
            "w_cat_id": "trouser",
            "k_cat_id": "trouser",
            "p_cat_id": "null",
            "cat_id": "men",
            "date": "2021-04-10 18:24:18",
            "product_title": "Striker Xt",
            "product_img1": "PANTS AIRSOFT 0000000.png",
            "product_img2": "PANTS AIRSOFT 000000.png",
            "product_img3": "PANTS AIRSOFT 00000.png",
            "product_price": "50",
            "product_desc": "striker xt pants tactical pants",
            "stock": "3",
            "product_rating": "5",
            "product_color": "green, tan",
            "product_size": "xl, x ,xxl, m",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.384Z",
            "updatedAt": "2022-03-17T04:14:25.384Z"
        },
        {
            "_id": "6232b5a18a80dc3de45366a5",
            "product_id": "13",
            "m_cat_id": "shoes",
            "w_cat_id": "shoes",
            "k_cat_id": "shoes",
            "p_cat_id": "shoes",
            "cat_id": "men",
            "date": "2021-04-10 15:34:21",
            "product_title": "men shoes",
            "product_img1": "sh3.jpg",
            "product_img2": "sh2.jpg",
            "product_img3": "sh1.jpg",
            "product_price": "25",
            "product_desc": "men shoes",
            "product_keyword": "men shoes",
            "stock": "10",
            "product_rating": "2",
            "product_color": "white",
            "product_size": "xl, x, m, xxl",
            "product_isFeatured": false,
            "product_isLatest": false,
            "createdAt": "2022-03-17T04:14:25.459Z",
            "updatedAt": "2022-03-17T04:14:25.459Z",
            "__v": 0
        }
    ]
}

export default DUMMYPRODUCTS